Worked on article page and model to be dynamic
Hkaar/7Books pull request #161
Opened 2024-12-12 17:46 UTC by Nashon-Juma

Integrate Spatie Media Library for image management

2024-12-12 17:57 UTC, Nashon-Juma commented
Hello @Hkaar just trying out to see if you can allow me to start contributing in this your amazing project feel free to reach out here-> https://nashonjuma.online

2024-12-13 04:46 UTC, Hkaar commented
Hello @Nashon-Juma, glad to see you contributing to the project, please wait while i will review the changes you
made in this pull request. Thank you!

2024-12-13 04:54 UTC, Hkaar commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->id()->primaryKey();
It's not necessary to call `->primaryKey()` here, because `->id()` aldready sets that column as a primary key in the db.

2024-12-13 04:55 UTC, Hkaar commented on database/migrations/2024_04_01_133925_orders.php
> +            $table->id()->primaryKey;
Remove unnecessary method call to `->primaryKey`, because `->id()` already sets the column to a primary key in the db.

2024-12-13 05:05 UTC, Hkaar commented on app/Models/Article.php
> +    public function registerMediaCollections(): void
Perhaps add a doc comment to explain what the method is used for?

2024-12-13 05:06 UTC, Hkaar commented on app/Http/Controllers/ArticleController.php
> +    public function show($slug)
Please consider adding an explicit type to the $slug param

2024-12-13 05:12 UTC, Hkaar requested changes
Your first contribution is great! just that has some minor issues related to:

- Consider removing unnecessary method calls that don't add value.
- Look into adding explicit type declarations to parameters.
- And consider adding a doc comment for extra clarity to some methods for future contributors.

Overall, good work on your first contribution! Keep up the good effort champ!

2024-12-13 09:37 UTC, Nashon-Juma reviewed
@Hkaar Worked on alll reviews you earlier on provided

2024-12-13 11:10 UTC, Hkaar approved these changes
Good job @Nashon-Juma! Thank you for taking your time to contribute to the project, i will be merging the pull request.

2024-12-13 11:11 UTC, merged

2024-12-13 12:17 UTC, Nashon-Juma commented
Okay will continue contributing on my free time till I'm fully satisfied its completely done
@Hkaar can I integrate tailwind into some pages of the app for easy development

2024-12-13 15:22 UTC, Hkaar commented
Good to have you onboard @Nashon-Juma, and yes you can integrate tailwind into some pages if you like. But i recommend to use Vite rather than a CDN link as suggested in the tailwind docs, to reduce the bundle size and fit with the existing build system.